### ISSUE TITLE
weatherscript.py fails occasionally

### ISSUE THREAD

**Issue by ssgodfrey** [apierz/nerdbar.widget#1]
I am really enjoying your nerdbar setup, but I am having an issue with the weather script failing about every-other run and dumping python error output across the bar. Here is the output:

```python
Traceback (most recent call last):
  File "./weatherscript.py", line 80, in <module>
    main()
  File "./weatherscript.py", line 63, in main
    data['query']['results']['channel']['item']['forecast'][4]['code'] + '@' +
TypeError: 'NoneType' object is not subscriptable
```

Not sure if you are having this issue too.

**Comment by apierz** [comment]
I have also run into this problem. It's proven difficult to debug since I'm not able to repeat the error at will. I am currently testing a couple of fixes for it that seem promising so if they work I should have the fixed script up in a day or two.

**Comment by ssgodfrey** [comment]
Cool. I made some temporary changes by adding a catch block to return
'--@99' from the script has a typeerror. In the widget, I assign null
values if the weather data fails to return, as well as some conditional
index changes to make sure the sysinfo data comes through.

I can post a diff of my changes later if desired.

Thanks!

On Thu, Dec 15, 2016, 1:37 PM Andy Pierz <notifications@github.com> wrote:

I have also run into this problem. It's proven difficult to debug since I'm
not able to repeat the error at will. I am currently testing a couple of
fixes for it that seem promising so if they work I should have the fixed
script up in a day or two.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/apierz/nerdbar.widget/issues/1#issuecomment-267422469>,
or mute the thread

**Comment by apierz** [comment]
My fix was probably similar to yours. I haven't noticed the error since implementing it so I pushed it to master.
