### ISSUE TITLE
Simple `git clone` doesn't work for installation

### ISSUE THREAD

**Issue by Amar1729** [apierz/nerdbar.widget#2]
There seem to be a few problems for installing this widget:
* the font isn't installed by default (so make sure to have people install this font? or specify a few fallback fonts in background.coffee?)
* the widget assumes all the scripts to be under `~/.kwm/scripts` but I don't think you ever specify to move or copy the directory there (could either update the README or change the script locations in your relevant .coffee and .sh files)
* FontAwesome and All-the-icons also aren't typically installed system-wide so maybe you could include them in the git repo, and then source them as a stylesheet from background.coffee? I think that's the typical convention for local usage but I'm not sure.

Just wanted to provide some suggestions, since this seems like a really cool bar!

**Comment by apierz** [comment]
Good points. I've made update to the README to make the installation more clear and I'll work on changing the script location to make it easier to install.
