### ISSUE TITLE
Remove torrent and make bottom left bar spotify Compatible

### ISSUE THREAD

**Issue by 0Arian** [apierz/nerdbar.widget#3]
Think you can do this? I have no clue how to :D Thanks!

**Comment by airrbearr** [comment]
Also I see you use deluge but you the bottom left bar to work with a complete different torrent client. Just what is going here????

**Comment by apierz** [comment]
I briefly switched to Deluge when Transmission was having malware issues but I like having my torrent client as a daemon. The ability to control it from the terminal and thus make widgets with the outputs is a nice bonus.

It looks like someone has written a Spotify command line interface so I can see if I can get it to work.

**Comment by apierz** [comment]
Ok, there is now a Spotify widget included, just turn off or delete the other one and 

`brew install shpotify` to make it work.
